# Generated by Django 5.2.6 on 2025-12-03 00:19

import backend.utils.generarCodigo
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entrada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Disponible", "Disponible"),
                            ("Reservada", "Reservada"),
                            ("Vendida", "Vendida"),
                            ("Cancelada", "Cancelada"),
                        ],
                        default="Disponible",
                        max_length=20,
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        default=backend.utils.generarCodigo.generar_codigo,
                        editable=False,
                        max_length=12,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reservar_hasta", models.DateTimeField()),
            ],
        ),
    ]
