# Generated by Django 5.2.6 on 2025-12-03 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("conciertos", "0001_initial"),
        ("entradas", "0001_initial"),
        ("pagos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="entrada",
            name="pago",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pagos",
                to="pagos.pago",
            ),
        ),
        migrations.AddField(
            model_name="entrada",
            name="tipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tipos",
                to="conciertos.tipoentrada",
            ),
        ),
    ]
