# Generated by Django 5.2.6 on 2026-01-18 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entradas", "0004_reserva_task_id_alter_entrada_precio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserva",
            name="cancelada",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reserva",
            name="vencio",
            field=models.BooleanField(default=False),
        ),
    ]
