# Generated by Django 5.2.6 on 2026-01-19 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conciertos", "0011_alter_concierto_limite_reserva_total_and_more"),
        ("entradas", "0005_reserva_cancelada_reserva_vencio"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserva",
            name="concierto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservas",
                to="conciertos.concierto",
            ),
        ),
    ]
