# Generated by Django 5.2.6 on 2026-01-23 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entradas", "0007_alter_reserva_concierto"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserva",
            name="pagado",
            field=models.BooleanField(default=False),
        ),
    ]
