# Generated by Django 5.2.6 on 2026-01-24 04:13

import django.db.models.deletion
import entradas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entradas", "0010_entrada_qr_token"),
        ("pagos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entrada",
            name="pago",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="entradas",
                to="pagos.pago",
            ),
        ),
        migrations.AlterField(
            model_name="entrada",
            name="qr_token",
            field=models.CharField(
                default=entradas.models.generar_qr_token_unico,
                editable=False,
                max_length=64,
                unique=True,
            ),
        ),
    ]
