# Generated by Django 5.2.6 on 2025-12-03 00:19

import backend.utils.validarImagen
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Ciudad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name="Lugar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("direccion", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Provincia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="TipoEntrada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cantidad_total", models.PositiveIntegerField()),
                ("limite_reserva", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Artista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("pais_origen", models.CharField(max_length=120)),
                (
                    "imagen",
                    models.ImageField(
                        upload_to="artistas/",
                        validators=[
                            backend.utils.validarImagen.validar_tamano_imagen,
                            backend.utils.validarImagen.validar_cuadrada,
                        ],
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="categorias",
                        to="conciertos.categoria",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Concierto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("descripcion", models.TextField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("programado", "Programado"),
                            ("agotado", "Agotado"),
                            ("finalizado", "Finalizado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="Programado",
                        max_length=20,
                    ),
                ),
                (
                    "mood",
                    models.CharField(
                        choices=[
                            ("bailable", "Para bailar"),
                            ("fiestero", "Fiestero"),
                            ("chill", "Chill"),
                            ("romantico", "Romántico"),
                            ("intimo", "Íntimo"),
                            ("energetico", "Enérgico"),
                        ],
                        max_length=50,
                    ),
                ),
                ("fecha", models.DateField()),
                ("show_hora", models.TimeField()),
                ("puertas_hora", models.TimeField()),
                ("limite_reserva_total", models.PositiveIntegerField()),
                (
                    "imagen",
                    models.ImageField(
                        upload_to="conciertos/",
                        validators=[
                            backend.utils.validarImagen.validar_tamano_imagen,
                            backend.utils.validarImagen.validar_cuadrada,
                        ],
                    ),
                ),
                (
                    "artista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="artistas",
                        to="conciertos.artista",
                    ),
                ),
            ],
        ),
    ]
