# Generated by Django 5.2.6 on 2025-12-03 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("conciertos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="concierto",
            name="organizador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organizadores",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="lugar",
            name="ciudad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ciudades",
                to="conciertos.ciudad",
            ),
        ),
        migrations.AddField(
            model_name="concierto",
            name="lugar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lugares",
                to="conciertos.lugar",
            ),
        ),
        migrations.AddField(
            model_name="ciudad",
            name="provincia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="provincias",
                to="conciertos.provincia",
            ),
        ),
        migrations.AddField(
            model_name="tipoentrada",
            name="evento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eventos",
                to="conciertos.concierto",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lugar",
            unique_together={("nombre", "ciudad")},
        ),
        migrations.AlterUniqueTogether(
            name="ciudad",
            unique_together={("nombre", "provincia")},
        ),
        migrations.AlterUniqueTogether(
            name="tipoentrada",
            unique_together={("nombre", "evento")},
        ),
    ]
