# Generated by Django 5.2.6 on 2026-01-04 22:15

import backend.utils.validarImagen
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conciertos", "0005_artista_estado_lugar_estado_alter_artista_imagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concierto",
            name="imagen",
            field=models.ImageField(
                upload_to="conciertos/",
                validators=[
                    backend.utils.validarImagen.validar_tamano_imagen,
                    backend.utils.validarImagen.validar_formato_imagen,
                    backend.utils.validarImagen.validar_cuadrada,
                ],
            ),
        ),
        migrations.CreateModel(
            name="ConciertoMeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("estado", "Estado"), ("mood", "Mood")], max_length=20
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Valor interno, ej: borrador, chill", max_length=30
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Texto visible, ej: Borrador, Chill", max_length=50
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["orden", "nombre"],
                "unique_together": {("tipo", "codigo")},
            },
        ),
        migrations.AlterField(
            model_name="concierto",
            name="estado",
            field=models.ForeignKey(
                limit_choices_to={"tipo": "estado"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="conciertos_por_estado",
                to="conciertos.conciertometa",
            ),
        ),
        migrations.AlterField(
            model_name="concierto",
            name="mood",
            field=models.ForeignKey(
                limit_choices_to={"tipo": "mood"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="conciertos_por_mood",
                to="conciertos.conciertometa",
            ),
        ),
    ]
