# Generated by Django 5.2.6 on 2026-01-05 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conciertos", "0007_rename_estado_artista_activo_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tipoentrada",
            unique_together={("nombre", "evento")},
        ),
    ]
