# Generated by Django 5.2.6 on 2026-01-19 00:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conciertos", "0010_tipoentrada_activo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concierto",
            name="limite_reserva_total",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(2),
                    django.core.validators.MaxValueValidator(8),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="tipoentrada",
            name="cantidad_total",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MaxValueValidator(10000)]
            ),
        ),
        migrations.AlterField(
            model_name="tipoentrada",
            name="limite_reserva",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MaxValueValidator(6)]
            ),
        ),
        migrations.AlterField(
            model_name="tipoentrada",
            name="precio",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(100.0),
                    django.core.validators.MaxValueValidator(1000000.0),
                ],
            ),
        ),
    ]
