# Generated by Django 5.2.6 on 2026-01-27 21:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conciertos", "0013_alter_tipoentrada_options_concierto_duracion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concierto",
            name="duracion",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
