# Generated by Django 5.2.6 on 2026-01-27 21:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conciertos", "0014_alter_concierto_duracion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concierto",
            name="duracion",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(30),
                    django.core.validators.MaxValueValidator(300),
                ]
            ),
        ),
    ]
