# Generated by Django 5.2.6 on 2026-01-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conciertos", "0015_alter_concierto_duracion"),
    ]

    operations = [
        migrations.AddField(
            model_name="concierto",
            name="finalizar_task_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="concierto",
            name="iniciar_task_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
