# Generated by Django 5.2.6 on 2026-01-29 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conciertos", "0016_concierto_finalizar_task_id_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tipoentrada",
            unique_together=set(),
        ),
    ]
