# Generated by Django 5.2.6 on 2026-01-29 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conciertos", "0017_alter_tipoentrada_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tipoentrada",
            options={"ordering": ["-activo", "precio"]},
        ),
    ]
