export const endpoints = {
  conciertos: {
    provincias: "/conciertos/provincias/",
    ciudades: "/conciertos/ciudades/",
    registrar_lugar: "/conciertos/registrar_lugar/",
    lugares: "/conciertos/lugares/",
    modificar_lugar: (id) => `/conciertos/modificar_lugar/${id}`,
    categorias: "/conciertos/categorias/",
    paises: "/conciertos/paises/",
    crear_artista: "/conciertos/crear_artista/",
    artistas: "/conciertos/artistas/",
    modificar_artista: (id) => `/conciertos/modificar_artista/${id}`,
    conciertoMeta: "/conciertos/concierto-meta/",
    crear_concierto: "/conciertos/crear_concierto/",
    conciertos: "/conciertos/conciertos/",
    modificar_concierto: (id) => `/conciertos/modificar_concierto/${id}`,
    detalles_concierto: (id) => `/conciertos/detalles_concierto/${id}`,
    cancelar_concierto: (id) => `/conciertos/cancelar_concierto/${id}`,
    agregar_tipo: "/conciertos/agregar_tipo/",
    cancelar_tipo: (id) => `/conciertos/cancelar_tipo/${id}`,
    cancelar_cantidad_tipo: (id) => `/conciertos/cancelar_cantidad_tipo/${id}`,
    modificar_tipo: (id) => `/conciertos/modificar_tipo/${id}`,
    agregar_entradas_tipo: (id) => `/conciertos/agregar_entradas_tipo/${id}`,
    tipos_concierto: (id) => `/conciertos/tipos_concierto/${id}`,
    tipos_reservar: (id) => `/conciertos/tipos_reservar/${id}`,
  },
  entradas: {
    reservar: "/entradas/reservar/",
    cancelar_reserva: "/entradas/cancelar_reserva/",
    detalles_reserva: "/entradas/detalles_reserva/",
    quitar_entrada: (id) => `/entradas/quitar_entrada/${id}`,
    entradas: "/entradas/entradas/",
  },
  pagos: {
    pagar_reserva: "/pagos/pagar_reserva/",
    pagos: "/pagos/pagos/",
  },
  usuarios: {
    registrarse: "/usuarios/registrarse/",
    login: "/usuarios/login/",
    refresh: "/usuarios/refresh/",
    logout: "/usuarios/logout/",
    me: "/usuarios/me/",
    actualizar_perfil: "/usuarios/actualizar_perfil/",
    actualizar_password: "/usuarios/actualizar_password/",
    crear_usuario: "/usuarios/admin/crear_usuario/",
    modificar_usuario: (id) => `/usuarios/admin/modificar_usuario/${id}`,
    usuarios: "/usuarios/admin/listar_usuarios/",
    detalles_usuario: (id) => `/usuarios/admin/detalles_usuario/${id}`,
    estadisticas_organizador: (id) => `/usuarios/estadisticas_organizador/${id}`,
  }
};
