# Generated by Django 5.2.6 on 2025-11-09 15:31

import conciertos.models
import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        choices=[
                            ("Rock", "Rock"),
                            ("Pop", "Pop"),
                            ("Metal", "Metal"),
                            ("Indie", "Indie"),
                            ("Hip-Hop", "Hip-Hop"),
                            ("Electronica", "Electronica"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ciudad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name="Provincia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Rol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        choices=[
                            ("Administrador", "Administrador"),
                            ("Organizador", "Organizador"),
                            ("Cliente", "Cliente"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Artista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("pais_origen", models.CharField(max_length=120)),
                ("imagen", models.ImageField(upload_to="artistas/")),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="conciertos.categoria",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lugar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("direccion", models.CharField(max_length=255)),
                (
                    "ciudad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="conciertos.ciudad",
                    ),
                ),
            ],
            options={
                "unique_together": {("nombre", "ciudad")},
            },
        ),
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("descripcion", models.TextField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Programado", "Programado"),
                            ("En curso", "En curso"),
                            ("Finalizado", "Finalizado"),
                            ("Cancelado", "Cancelado"),
                        ],
                        default="Programado",
                        max_length=20,
                    ),
                ),
                ("fecha", models.DateField()),
                ("show_hora", models.TimeField()),
                ("puertas_hora", models.TimeField()),
                ("limite_reserva_total", models.PositiveIntegerField()),
                ("imagen", models.ImageField(upload_to="eventos/")),
                (
                    "artista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="conciertos.artista",
                    ),
                ),
                (
                    "lugar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="conciertos.lugar",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ciudad",
            name="provincia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="conciertos.provincia"
            ),
        ),
        migrations.CreateModel(
            name="TipoEntrada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cantidad_total", models.PositiveIntegerField()),
                ("limite_reserva", models.PositiveIntegerField()),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="conciertos.evento",
                    ),
                ),
            ],
            options={
                "unique_together": {("nombre", "evento")},
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "genero",
                    models.CharField(
                        choices=[
                            ("Hombre", "Hombre"),
                            ("Mujer", "Mujer"),
                            ("Otro", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fecha_nacimiento", models.DateField()),
                ("edad", models.PositiveIntegerField(blank=True, null=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Los grupos a los que pertenece este usuario.",
                        related_name="usuario_set",
                        to="auth.group",
                    ),
                ),
                (
                    "rol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="conciertos.rol"
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Permisos específicos para este usuario.",
                        related_name="usuario_set",
                        to="auth.permission",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Pago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        default=conciertos.models.generar_codigo,
                        editable=False,
                        max_length=12,
                        unique=True,
                    ),
                ),
                ("cant_entradas", models.PositiveIntegerField()),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha_hora", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="conciertos.usuario",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="evento",
            name="organizador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="conciertos.usuario"
            ),
        ),
        migrations.CreateModel(
            name="Entrada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Disponible", "Disponible"),
                            ("Reservada", "Reservada"),
                            ("Vendida", "Vendida"),
                            ("Cancelada", "Cancelada"),
                        ],
                        default="Disponible",
                        max_length=20,
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        default=conciertos.models.generar_codigo,
                        editable=False,
                        max_length=12,
                        unique=True,
                    ),
                ),
                ("reserva_expira", models.DateTimeField(blank=True, null=True)),
                (
                    "pago",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="conciertos.pago",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="conciertos.tipoentrada",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="conciertos.usuario",
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="ciudad",
            unique_together={("nombre", "provincia")},
        ),
    ]
