# Generated by Django 5.2.6 on 2025-11-09 20:23

import conciertos.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conciertos", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="usuario",
            managers=[
                ("objects", conciertos.models.UsuarioManager()),
            ],
        ),
    ]
