# Generated by Django 5.2.6 on 2025-09-20 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conciertos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="edad",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="entrada",
            name="estado",
            field=models.CharField(
                choices=[
                    ("Disponible", "Disponible"),
                    ("Reservada", "Reservada"),
                    ("Vendida", "Vendida"),
                    ("Cancelada", "Cancelada"),
                ],
                default="Disponible",
            ),
        ),
        migrations.AlterField(
            model_name="evento",
            name="cant_entradas",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="evento",
            name="estado",
            field=models.CharField(
                choices=[
                    ("Programado", "Programado"),
                    ("En curso", "En curso"),
                    ("Finalizado", "Finalizado"),
                    ("Cancelado", "Cancelado"),
                ],
                default="Programado",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pago",
            name="fecha_hora",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
