# Generated by Django 5.2.6 on 2025-09-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conciertos", "0002_usuario_edad_alter_entrada_estado_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evento",
            name="precio",
        ),
        migrations.AddField(
            model_name="usuario",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usuario",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="entrada",
            name="estado",
            field=models.CharField(
                choices=[
                    ("Disponible", "Disponible"),
                    ("Reservada", "Reservada"),
                    ("Vendida", "Vendida"),
                    ("Cancelada", "Cancelada"),
                ],
                default="Disponible",
                max_length=20,
            ),
        ),
    ]
