# Generated by Django 5.2.6 on 2026-01-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conciertos", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pais",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
