# Generated by Django 5.2.6 on 2025-11-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conciertos", "0002_alter_usuario_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usuario",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
