# Generated by Django 5.2.6 on 2026-01-02 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conciertos", "0003_pais"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artista",
            name="pais_origen",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="paises",
                to="conciertos.pais",
            ),
        ),
    ]
