# Generated by Django 5.2.6 on 2025-09-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conciertos", "0003_remove_evento_precio_usuario_is_staff_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can log into this admin site.",
                verbose_name="staff status",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
    ]
