# Generated by Django 5.2.6 on 2025-09-29 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conciertos", "0004_alter_usuario_is_staff_alter_usuario_is_superuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="entrada",
            name="reserva_expira",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
