# Generated by Django 5.2.6 on 2026-01-03 23:18

import backend.utils.validarImagen
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conciertos", "0004_alter_artista_pais_origen"),
    ]

    operations = [
        migrations.AddField(
            model_name="artista",
            name="estado",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="lugar",
            name="estado",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="artista",
            name="imagen",
            field=models.ImageField(
                upload_to="artistas/",
                validators=[
                    backend.utils.validarImagen.validar_tamano_imagen,
                    backend.utils.validarImagen.validar_formato_imagen,
                    backend.utils.validarImagen.validar_cuadrada,
                ],
            ),
        ),
    ]
