# Generated by Django 5.2.6 on 2025-11-09 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conciertos", "0004_usuario_date_joined_usuario_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="last_login",
        ),
    ]
