# Generated by Django 5.2.6 on 2025-10-03 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conciertos", "0005_entrada_reserva_expira"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="last_login",
        ),
    ]
