# Generated by Django 5.2.6 on 2026-01-04 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conciertos", "0006_alter_concierto_imagen_conciertometa_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="artista",
            old_name="estado",
            new_name="activo",
        ),
        migrations.RenameField(
            model_name="lugar",
            old_name="estado",
            new_name="activo",
        ),
        migrations.AlterField(
            model_name="concierto",
            name="estado",
            field=models.ForeignKey(
                default=1,
                limit_choices_to={"tipo": "estado"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="conciertos_por_estado",
                to="conciertos.conciertometa",
            ),
        ),
    ]
