# Generated by Django 5.2.6 on 2025-10-03 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "conciertos",
            "0006_remove_usuario_date_joined_remove_usuario_is_staff_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="is_active",
        ),
    ]
