# Generated by Django 5.2.6 on 2025-11-09 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conciertos", "0006_usuario_date_joined_usuario_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
