# Generated by Django 5.2.6 on 2025-11-10 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("conciertos", "0007_alter_usuario_is_active_alter_usuario_is_staff_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="usuario_set", to="auth.group"
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True, related_name="usuario_set", to="auth.permission"
            ),
        ),
    ]
