# Generated by Django 5.2.6 on 2026-01-05 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conciertos", "0008_sync_tipoentrada_evento"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tipoentrada",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="concierto",
            name="estado",
            field=models.ForeignKey(
                limit_choices_to={"tipo": "estado"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="conciertos_por_estado",
                to="conciertos.conciertometa",
            ),
        ),
        migrations.AlterField(
            model_name="tipoentrada",
            name="evento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tipos_entrada",
                to="conciertos.concierto",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tipoentrada",
            unique_together={("nombre", "evento")},
        ),
    ]
