# Generated by Django 5.2.6 on 2025-11-21 23:54

import conciertos.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conciertos", "0008_alter_usuario_groups_alter_usuario_user_permissions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entrada",
            name="cliente",
        ),
        migrations.RemoveField(
            model_name="entrada",
            name="reserva_expira",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="edad",
        ),
        migrations.AlterField(
            model_name="artista",
            name="imagen",
            field=models.ImageField(
                upload_to="artistas/",
                validators=[
                    conciertos.models.validar_tamano_imagen,
                    conciertos.models.validar_cuadrada,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="categoria",
            name="nombre",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="evento",
            name="imagen",
            field=models.ImageField(
                upload_to="eventos/",
                validators=[
                    conciertos.models.validar_tamano_imagen,
                    conciertos.models.validar_cuadrada,
                ],
            ),
        ),
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reservar_hasta", models.DateTimeField()),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        unique=True,
                    ),
                ),
                ("entradas", models.ManyToManyField(to="conciertos.entrada")),
            ],
        ),
    ]
