# Generated by Django 5.2.6 on 2025-11-22 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "conciertos",
            "0009_remove_entrada_cliente_remove_entrada_reserva_expira_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reserva",
            name="entradas",
        ),
        migrations.AddField(
            model_name="entrada",
            name="reserva",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="conciertos.reserva",
            ),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="cliente",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
