# Generated by Django 5.2.6 on 2026-01-20 23:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conciertos", "0011_alter_concierto_limite_reserva_total_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tipoentrada",
            name="cantidad_total",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10000),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="tipoentrada",
            name="limite_reserva",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(6),
                ]
            ),
        ),
    ]
