# Generated by Django 5.2.6 on 2026-01-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conciertos", "0012_alter_tipoentrada_cantidad_total_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tipoentrada",
            options={"ordering": ["precio"]},
        ),
        migrations.AddField(
            model_name="concierto",
            name="duracion",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
