# Generated by Django 5.2.6 on 2026-01-12 20:18

import backend.utils.generarCodigo
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("conciertos", "0009_alter_tipoentrada_unique_together_and_more"),
        ("pagos", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reservar_hasta", models.DateTimeField()),
                (
                    "cliente",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Entrada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("disponible", "Disponible"),
                            ("reservada", "Reservada"),
                            ("vendida", "Vendida"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="disponible",
                        max_length=20,
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        default=backend.utils.generarCodigo.generar_codigo_unico_entrada,
                        editable=False,
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "pago",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pagos",
                        to="pagos.pago",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entradas",
                        to="conciertos.tipoentrada",
                    ),
                ),
                (
                    "reserva",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservas",
                        to="entradas.reserva",
                    ),
                ),
            ],
        ),
    ]
