# Generated by Django 5.2.6 on 2026-01-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entradas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserva",
            name="activo",
            field=models.BooleanField(default=True),
        ),
    ]
