# Generated by Django 5.2.6 on 2026-01-17 20:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entradas", "0003_alter_reserva_cliente"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserva",
            name="task_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="entrada",
            name="precio",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(100.0),
                    django.core.validators.MaxValueValidator(1000000.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="reservar_hasta",
            field=models.DateTimeField(editable=False),
        ),
    ]
