# Generated by Django 5.2.6 on 2026-01-23 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("entradas", "0008_reserva_pagado"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reserva",
            old_name="pagado",
            new_name="pagada",
        ),
    ]
