# Generated by Django 5.2.6 on 2026-01-24 03:02

import uuid
from django.db import migrations, models

def generar_tokens(apps, schema_editor):
    Entrada = apps.get_model("entradas", "Entrada")
    for entrada in Entrada.objects.all():
        entrada.qr_token = uuid.uuid4()
        entrada.save(update_fields=["qr_token"])

class Migration(migrations.Migration):

    dependencies = [
        ("entradas", "0009_rename_pagado_reserva_pagada"),
    ]

    operations = [
        migrations.AddField(
            model_name="entrada",
            name="qr_token",
            field=models.UUIDField(null=True),
        ),
        migrations.RunPython(generar_tokens),
        migrations.AlterField(
            model_name="entrada",
            name="qr_token",
            field=models.UUIDField(unique=True, editable=False),
        ),
    ]
