# Generated by Django 5.2.6 on 2025-12-03 00:19

import backend.utils.generarCodigo
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        default=backend.utils.generarCodigo.generar_codigo,
                        editable=False,
                        max_length=12,
                        unique=True,
                    ),
                ),
                ("cant_entradas", models.PositiveIntegerField()),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha_hora", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
